### ISSUE TITLE
v1.0.0 roadmap

### ISSUE THREAD

**Issue by arkivanov** [arkivanov/Decompose#112]
Required tasks:

- [x] Stabilize [Compose Animations API](https://arkivanov.github.io/Decompose/extensions/compose/#animations-experimental) (see #110)
- [x] Improve the "Check failed" error message (see #77)
- [x] Comply with the new [predictive back gesture](https://developer.android.com/about/versions/13/features/predictive-back-gesture) in Android 13 (see #156)
- [x] Move `Router` to `stack` sub-package and rename it to `StackRouter` (see #134)
- [x] Remove all deprecated code
- [x] Add extensions for Value (see #200)
- [x] Change naming in samples from `Some` + `SomeComponent` to `SomeComponent` + `DefaultSomeComponent`
- [x] Update all Android dependencies (#303)

Desired tasks:

- [ ] Stabilize [Web Routing API](https://arkivanov.github.io/Decompose/router/browser-history/) (see #111)
- [ ] Stabilize [extensions-android](https://github.com/arkivanov/Decompose/tree/master/extensions-android) module
- [ ] Support Compose for iOS and macOS (see #74)
- [x] Allow safe `Router` access from `childFactory` function
- [ ] Remove `extensions-compose-jetpack` module (see #11)
- [x] Add child overlay navigation

**Comment by Solace-Studios** [comment]
@arkivanov For someone starting a new project, would you still recommend using Decompose in its current state?

**Comment by arkivanov** [comment]
@Solace-Studios Decompose is already used in production in various projects. Version `1.0.0` should be released within a month, however I don't expect any significant API changes. If you like Decompose then absolutely go ahead and use it.

**Comment by Solace-Studios** [comment]
@arkivanov That's great news! I actually just found out about it. I've been looking into RIBs as an architecture for a new cross platform comparable product to Uber these last few weeks. I was wondering how I was going to support navigation, recovery from process death, and integrate Compose and SwiftUI. This just happens to support all those things it seems. I'm running through the sample, I like it so far. Are you aware of any more companies using Decompose than [this list?](https://github.com/badoo/Decompose/issues/81)

**Comment by arkivanov** [comment]
> Are you aware of any more companies using Decompose

Yes I am, however I'm not sure if I can mentioned anything about it, sorry. You can try [searching](https://github.com/search?q=%22com.arkivanov.decompose%22&type=code) through GitHub, there are 3k+ code search results.

**Comment by arkivanov** [comment]
Version `1.0.0` is released!
